### ISSUE TITLE
Unable to use Heikin Ashi with new bot

### ISSUE THREAD

**Issue by italathi** [conor19w/Binance-Futures-Trading-Bot#18]
The Heikin Ashi strategy in TradingStrats.py refers to variables in the deprecated Bot. 

Does anyone have an updated Heikin Ashi function working with the new Bot ?

**Comment by conor19w** [comment]
What are you referring to? It works with the current backtester. Neither bot has heikin ashi yet is that what you mean?

**Comment by conor19w** [comment]
Closing as I got no reply
