### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ricardospinoza** [conor19w/Binance-Futures-Trading-Bot#34]
![image](https://user-images.githubusercontent.com/4679105/219903626-d27599af-3d51-4429-93be-f5ffd99ee67b.png)
Coins Tradeable : ['STGUSDT']
Loading Price Data
Loading STGUSDT
Data doesnt exist in path: .//price_data//STGUSDT_01-02-23_18-02-23.joblib, Downloading Data to specified path now...
Downloading CandleStick Data for STGUSDT...
Saving Price data
Download Successful, Loading Data now
Aligning Data Sets... This may take a few minutes
['STGUSDT']
15m OHLC Candle Sticks from 01-02-23 to 18-02-23
Account Balance:  100.0

single positional indexer is out-of-bounds

Settings:
leverage: 5
order_size: 0.0125
fee: 0.00036
symbol = []

Overall Stats based on all coins
Trades Made:  0
Process Process-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\desenvolvimento\projetos\python\Binance-Futures-Trading-Bot-main\Backtester.py", line 483, in run_backtester
    print("Accuracy: ", f"{(len(winning_trades) / tradeNO) * 100}%", "\n")
ZeroDivisionError: division by zero
Coins Tradeable : ['STGUSDT']
Loading Price Data
Loading STGUSDT
Aligning Data Sets... This may take a few minutes
['STGUSDT']
15m OHLC Candle Sticks from 01-02-23 to 18-02-23
Account Balance:  100.0

**Comment by conor19w** [comment]
I should fix the way this is handled, but this is not an error really. It just means no trades were taken over that period. Broaden the testing period or add more coins to get trades. Unless you are using a custom strategy and maybe have not configured it correctly

**Comment by ricardospinoza** [comment]
ok. tks for feedback.

Em seg, 20 de fev de 2023 08:52, Conor White ***@***.***>
escreveu:
