### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by MrShadowDev** [conor19w/Binance-Futures-Trading-Bot#60]
![image](https://github.com/conor19w/Binance-Futures-Trading-Bot/assets/71973368/eecafca0-b83d-4a9e-a210-57afce825b07)

**Comment by conor19w** [comment]
Hey @MrShadowDev - have you installed all the required dependencies?
Looks like it can't find the ThreadedWebsocketManager from the python-binance library.

**Comment by MrShadowDev** [comment]
> Hey @MrShadowDev - have you installed all the required dependencies? Looks like it can't find the ThreadedWebsocketManager from the python-binance library.

yes ty
