### ISSUE TITLE
Just found you, it would be great if it works. But it doesn't work yet

### ISSUE THREAD

**Issue by cnstephen** [conor19w/Binance-Futures-Trading-Bot#65]
Same settings, why can I run it on Mac but not Windows? Mac has to shut down, both are run with vscode
I ran it successfully, But it keeps giving errors
In the latest version,I modified the api,symbols_to_trade = ['XRPUSDT']
 on OPUSDT,else, i have no buy

`19-06-2024 20:18:00 INFO: Account Balance: $10.064, Total profit: $0, PNL: $-0.027, Wins: 0, Losses: 0, Win/Loss ratio: Not available yet, Open Positions: 1
| Symbol   |   Position Size | Direction   |   Entry Price |   Market Price | TP             | SL             | Distance to TP (%)   | Distance to SL (%)   |       PNL |
|----------|-----------------|-------------|---------------|----------------|----------------|----------------|----------------------|----------------------|-----------|
| XRPUSDT  |             100 | LONG        |       0.49365 |       0.493383 | Not opened yet | Not opened yet | Not available yet    | Not available yet    | -0.026726 |
19-06-2024 20:18:00 WARNING: open_trade() - error occurred placing limit order on OPUSDT, OP: 1, tick_size: 0.0001 Entry price: 1.9083, trade direction: 1, Quantity: 161.6, Error Info: (BinanceAPIException(<Response [400]>, 400, '{"code":-4061,"msg":"Order\'s position side does not match user\'s setting."}'), 'TradeManager.py', 321), Error: APIError(code=-4061): Order's position side does not match user's setting.
19-06-2024 20:18:01 WARNING: open_trade() - error occurred placing limit order on BLURUSDT, OP: 0, tick_size: 0.0001 Entry price: 0.2632, trade direction: 1, Quantity: 1172, Error Info: (BinanceAPIException(<Response [400]>, 400, '{"code":-4061,"msg":"Order\'s position side does not match user\'s setting."}'), 'TradeManager.py', 321), Error: APIError(code=-4061): Order's position side does not match user's setting.`

**Comment by conor19w** [comment]
Position mode needs to be one way
![Screenshot_2024-06-19-13-31-20-47_ee1cec40dcf6eb3919ecbfc5d87e6719.jpg](https://github.com/conor19w/Binance-Futures-Trading-Bot/assets/63513457/3fb6621e-b9be-42c9-ac57-35da9e6ff1ec)

**Comment by conor19w** [comment]
Not sure if it will work on mac either, there are issues with linux systems so might be the case for mac also

**Comment by cnstephen** [comment]
But my windows can't run, I don't know why

**Comment by cnstephen** [comment]
First use windows

**Comment by cnstephen** [comment]
![858695151](https://github.com/conor19w/Binance-Futures-Trading-Bot/assets/81022834/f5aaac3d-22ee-4d3e-8f56-7a19257c9b95)

**Comment by cnstephen** [comment]
In the picture you posted, is there a web management interface?

**Comment by cnstephen** [comment]
hlpe

**Comment by cnstephen** [comment]
help
