### ISSUE TITLE
Backtest results

### ISSUE THREAD

**Issue by mujahidazamcsm** [conor19w/Binance-Futures-Trading-Bot#7]
Hi @conor19w  - 

I was just going thru the code.. great job!!.

Have u had the chance to run backtest on the various strategies? do u have the results already that we can have a look at?

I am planning to start the backtest.. but in case u have already done it.. plz share.

**Comment by conor19w** [comment]
No not currently but that's a good idea I'll add a section with that, Most of the strategies need a lot of work to be profitable I think.
Try from 15m chart and up, I would say one or two may have okay results on the 4hr chart.
They are just examples really to show how one would go about implementing a strategy.
Have a read of the README file I'd advise using the load_data functionality it will make back tests quicker and you'll be able to compare results as they will be from the same time frame.
