### ISSUE TITLE
Heikin_Ashi Strategy, TSL

### ISSUE THREAD

**Issue by mujahidazamcsm** [conor19w/Binance-Futures-Trading-Bot#8]
Hi @conor19w ,

Do u happen to have the heikin_ashi strategy? is it easy to incorporate in the current bot? 

Also TSL (trailing stop loss or trailing take profit) would be a great option to maximize profits. 

Do u have any plans to add these?

**Comment by conor19w** [comment]
Heikin_ashi could be implemented easily yes, I'll set up a suggestions section for these kind of requests.
The trailing Stop too can be implemented but I'd need specifics of how you want it to function, Join the discord and DM me or else email.
